Bump upcoming version in config

diff --git a/ci/tasks/repackage-with-official-artifacts.yml b/ci/tasks/repackage-with-official-artifacts.yml
--- a/ci/tasks/repackage-with-official-artifacts.yml
+++ b/ci/tasks/repackage-with-official-artifacts.yml
@@ -47,6 +47,19 @@ run:
         | tr -d "'"
     )
 
+    cd src/ssoca
+
+    git fetch
+
+    if ! git rev-parse "v${client_version}" | grep "$( git rev-parse HEAD )" ; then
+      # they don't exist; probably not yet released, so continue with source
+      echo 'WARN: expected server version not found in source repository'
+
+      exit
+    fi
+
+    cd ../..
+
     cd src/ssoca-clients
 
     curl -fLo /usr/local/bin/meta4-repo https://github.com/dpb587/metalink/releases/download/v0.2.0/meta4-repo-0.2.0-linux-amd64
